#!/bin/bash
#USAP Assignment 2 build kernel script
#Name: Dat LE
#Id: s3794387

#Path for Executables
GIT=/usr/bin/git
CP=/bin/cp
TAR=/bin/tar
MAKE=/usr/bin/make
MKDIR=/bin/mkdir
RM=/bin/rm
REBOOT=/sbin/reboot

#Path for git directories
myGIT="https://github.com/s3794387/USAP-Assignment2"
kernelGIT="https://github.com/raspberrypi/linux"

#Check out my repository
$GIT clone --depth=1 $myGIT

#Check out rasberry pi kernel
$GIT clone --depth=1 $kernelGIT


#Start Performance monitoring
sh USAP-Assignment2/performance_monitor &
monitor_pid=$!

#Build the kernel
cd linux
KERNEL=kernel7l
$MAKE bcm2711_defconfig

#Copy ".config" file to the right place
$CP USAP-Assignment2/.config linux/.config

$MAKE -j4 zImage modules dtbs

#Back up appropritate files in /boot
#These files will be compressed and saved as kernel_backup.tar.gz in linux folder
$MKDIR Backup
cd Backup
$MKDIR overlays
cd ..
sudo $CP /boot/*.dtb Backup
sudo $CP /boot/overlays/*.dtb* Backup/overlays
sudo $CP /boot/overlays/README Backup/overlays
sudo $CP /boot/$KERNEL.img

$TAR -zcvf kernel_backup.tar.gz Backup

#Copy new Kernel into /boot
sudo $MAKE modules_install
sudo $CP arch/arm/boot/dts/*.dtb /boot/
sudo $CP arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo $CP arch/arm/boot/dts/overlays/README /boot/overlays/

sudo $CP arch/arm/boot/zImage /boot/$KERNEL.img

#Reboot the system for the changes to take place
sudo $REBOOT

