#!/bin/bash
#USAP Assignment 2 Performance Monitoring Script

#Path for Executables
VCGENCMD=/usr/bin/vcgencmd

#Listen for USR1 signal to stop the process
trap "kill $$" USR1

#Performance monitoring
#Add headings
printf "%s\t%s\n" "TIMESTAMP" "TEMP(C)" "CLOCK(MHz)"> kernel_performance_data
printf "%20s\n" "_____________________________________________________" >> kernel_performance_data

#Monitor Temperature every 1 second
while true
do

	timestamp=$(date +%s)
	temp=$($VCGENCMD measure_temp | egrep -o '[0-9]*\.[0-9]*')
	clock=$($VCGENCMD measure_clock arm | grep '=[0-9]*' | cut -d '=' -f 1)
	printf "%s\t%s\n" "$timestamp" "$temp" "$clock" >> kernel_performance_data
	sleep 1
done

